- hosts: localhost
  become: true
  tasks:
  - name: Install nodejs
    apt: 
      name: nodejs

  - name: Install npm
    apt: 
      name: npm
  
  - name: Install nodejs request library
    npm: 
      registry: http://registry.npmjs.org/
      name: request
      global: yes
      state: present
