- hosts: localhost
  become: true

  tasks:
  - name: Install nodejs
    apt: 
      name: nodejs

  - name: Install npm
    apt: 
      name: npm
  
  - name: Install nodejs request library
    npm: 
      registry: http://registry.npmjs.org/
      name: request
      global: yes
      state: present

  - name: Download app repo
    git: 
      repo: https://github.com/m4rvin/MyApp
      dest: ./MyApp

  - name: Change file rights
    shell: sudo chmod +x MyApp/app/server.js 

  - name: execute app
    shell: nodejs ./MyApp/app/server.js &
