- hosts: localhost
  become: true
  tasks:
  - name: Install nodejs
    apt: 
      name: nodejs

  - name: Install npm
    apt: 
      name: npm
    
  - name: Install nodejs request library
    npm: 
      name: request
      state: present
